name: "create_long_term_knowledge"
description: "Creates a new LearningKnowledge entry for the user. Used when storing a new fact, insight, or concept in the knowledge base."
details: |
  Creates a new plain-text learning entry for the current user. 
  This action stores long-form knowledge as simple text — such as insights, learnings, summaries, or notes —
  that can later be retrieved or searched by the agent.

  **When to use:**
  - When an agent, user, or process learns something new worth remembering.
  - When you want to persist text-based knowledge linked to the user.

  **Input Params (JSON):**
    {
      "knowledge_type": "concept",
      "knowledge_blob": "Goroutines in Go allow concurrent execution of functions and are managed by the Go runtime."
    }

  **Output Example:**
    {
      "id": "123e4567-e89b-12d3-a456-426614174001",
      "knowledge_type": "concept",
      "knowledge_blob": "Goroutines in Go allow concurrent execution of functions and are managed by the Go runtime.",
      "created_at": "2025-10-12T14:00:00Z",
      "user_id": 42
    }

params:
  knowledge_type:
    type: string
    description: Type/category for learning (e.g., 'code_fact', 'concept', 'procedure')
    example: concept
  knowledge_blob:
    type: string
    description: The full text or content of the learned knowledge (unstructured, can be long).
    example: Goroutines in Go allow concurrent execution of functions and are managed by the Go runtime.
